In [1]:
import pandas as pd

In [2]:
from sklearn.datasets import load_iris

In [3]:
data=load_iris(as_frame=True).frame
data.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [4]:
from sklearn.model_selection import train_test_split
x=data.drop(columns='target')
y=data['target']

In [5]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=42)

In [6]:
from sklearn.naive_bayes import GaussianNB
model_GNB=GaussianNB()

In [7]:
model_GNB.fit(x_train, y_train)
y_pred=model_GNB.predict(x_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [8]:
from sklearn.metrics import accuracy_score, classification_report
accuracy_score(y_test, y_pred)

0.9777777777777777

In [9]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

In [10]:
#Multinomial naive bayes
url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"
sms=pd.read_csv(url, sep='\t', header=None, names=['label', 'message'])
sms.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
x=sms['message']
y=sms['label']

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()

In [13]:
x_vectorized=vectorizer.fit_transform(x)

In [14]:
x_vectorized.shape

(5572, 8713)

In [15]:
x_vectorized.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 8713))

In [16]:
from sklearn.naive_bayes import MultinomialNB
model_MNB=MultinomialNB()

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x_vectorized, y, test_size=0.3, random_state=42)

In [18]:
model_MNB.fit(x_train, y_train)
y_pred=model_MNB.predict(x_test)

In [19]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_test, y_pred)

0.9850478468899522

In [20]:
confusion_matrix(y_test, y_pred)

array([[1432,   16],
       [   9,  215]])

In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.99      0.99      0.99      1448
        spam       0.93      0.96      0.95       224

    accuracy                           0.99      1672
   macro avg       0.96      0.97      0.97      1672
weighted avg       0.99      0.99      0.99      1672